import { Conversation, Message, InventoryItem, Booking } from "@/lib/types";

export const sampleConversations: Conversation[] = [
  {
    id: "conv-1",
    contactName: "Twiga Foods",
    contactInitials: "TF",
    channel: "whatsapp",
    preview: "Looks great — send over the brand identity deck when ready",
    time: "2m ago",
    unread: 2,
    projectName: "Brand Identity Refresh",
    pipelineValue: "KES 450,000",
    status: "open",
  },
  {
    id: "conv-2",
    contactName: "Bidco Africa",
    contactInitials: "BA",
    channel: "email",
    preview: "Can we get a quote for the Mombasa Rd billboard?",
    time: "18m ago",
    unread: 1,
    projectName: "Billboard Inquiry",
    pipelineValue: "KES 120,000",
    status: "open",
  },
  {
    id: "conv-3",
    contactName: "Naivas",
    contactInitials: "NV",
    channel: "whatsapp",
    preview: "The research report is exactly what we needed. Thanks!",
    time: "1h ago",
    unread: 0,
    projectName: "Market Research Report",
    pipelineValue: "KES 280,000",
    status: "open",
  },
  {
    id: "conv-4",
    contactName: "P&G East Africa",
    contactInitials: "PG",
    channel: "whatsapp",
    preview: "We'd like to expand the scope to include digital screens",
    time: "3h ago",
    unread: 3,
    projectName: "Campaign Expansion",
    pipelineValue: "KES 890,000",
    status: "open",
  },
  {
    id: "conv-5",
    contactName: "Java House",
    contactInitials: "JH",
    channel: "email",
    preview: "Please review the attached proposal for Q3 campaign",
    time: "5h ago",
    unread: 0,
    projectName: "Q3 Campaign Proposal",
    pipelineValue: "KES 320,000",
    status: "open",
  },
  {
    id: "conv-6",
    contactName: "Unga Group",
    contactInitials: "UG",
    channel: "whatsapp",
    preview: "Hi, we're interested in your media placement services",
    time: "8h ago",
    unread: 1,
    projectName: "New Lead",
    pipelineValue: "KES 150,000",
    status: "open",
    autoReply: true,
  },
];

export const sampleMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "m1",
      conversationId: "conv-1",
      direction: "inbound",
      text: "Hi, we need a brand identity refresh for our new product line launching in Q3.",
      time: "10:12 AM",
      channel: "whatsapp",
      senderName: "Twiga Foods",
    },
    {
      id: "m2",
      conversationId: "conv-1",
      direction: "outbound",
      text: "Absolutely! We can put together a full brand identity package — logo, colour system, typography, and brand guidelines. Let me share our process deck.",
      time: "10:15 AM",
      channel: "whatsapp",
      senderName: "Brian Mwangi",
    },
    {
      id: "m3",
      conversationId: "conv-1",
      direction: "inbound",
      text: "That sounds perfect. When can we expect the first round of concepts?",
      time: "10:20 AM",
      channel: "whatsapp",
      senderName: "Twiga Foods",
    },
    {
      id: "m4",
      conversationId: "conv-1",
      direction: "outbound",
      text: "We typically deliver first concepts within 7 business days. I'll draft the SOW and share it by EOD.",
      time: "10:22 AM",
      channel: "whatsapp",
      senderName: "Brian Mwangi",
    },
    {
      id: "m5",
      conversationId: "conv-1",
      direction: "inbound",
      text: "Looks great — send over the brand identity deck when ready",
      time: "10:30 AM",
      channel: "whatsapp",
      senderName: "Twiga Foods",
    },
  ],
  "conv-2": [
    {
      id: "m6",
      conversationId: "conv-2",
      direction: "inbound",
      text: "Good morning, we're looking at billboard options along Mombasa Road for our new cooking oil campaign.",
      time: "9:45 AM",
      channel: "email",
      senderName: "Bidco Africa",
    },
    {
      id: "m7",
      conversationId: "conv-2",
      direction: "outbound",
      text: "Great choice — Mombasa Road has excellent visibility. We have a 12×4m super-size billboard available in the Industrial Area. Daily impressions are around 180K. Shall I send specs and pricing?",
      time: "9:52 AM",
      channel: "email",
      senderName: "Brian Mwangi",
    },
    {
      id: "m8",
      conversationId: "conv-2",
      direction: "inbound",
      text: "Can we get a quote for the Mombasa Rd billboard?",
      time: "9:58 AM",
      channel: "email",
      senderName: "Bidco Africa",
    },
  ],
  "conv-3": [
    {
      id: "m9",
      conversationId: "conv-3",
      direction: "outbound",
      text: "Hi, the market research report for your Nairobi Westlands expansion is ready. I've uploaded it to the client portal.",
      time: "8:30 AM",
      channel: "whatsapp",
      senderName: "Brian Mwangi",
    },
    {
      id: "m10",
      conversationId: "conv-3",
      direction: "inbound",
      text: "The research report is exactly what we needed. Thanks!",
      time: "9:15 AM",
      channel: "whatsapp",
      senderName: "Naivas",
    },
    {
      id: "m10b",
      conversationId: "conv-3",
      direction: "outbound",
      text: "Report uploaded to client portal — notification sent automatically",
      time: "8:30 AM",
      channel: "whatsapp",
          senderName: "Market Link",
          isAutomation: true,
        },
  ],
  "conv-4": [
    {
      id: "m11",
      conversationId: "conv-4",
      direction: "inbound",
      text: "The current billboard campaign is performing well. We'd like to expand the scope to include digital screens in Westlands and Kilimani.",
      time: "7:00 AM",
      channel: "whatsapp",
      senderName: "P&G East Africa",
    },
    {
      id: "m12",
      conversationId: "conv-4",
      direction: "outbound",
      text: "Great to hear! We have premium digital screens in both areas. Westlands Roundabout screens get 220K daily impressions. Let me put together an expanded proposal.",
      time: "7:15 AM",
      channel: "whatsapp",
      senderName: "Brian Mwangi",
    },
    {
      id: "m13",
      conversationId: "conv-4",
      direction: "inbound",
      text: "Perfect. Include pricing for both 30-second and 60-second loop slots.",
      time: "7:20 AM",
      channel: "whatsapp",
      senderName: "P&G East Africa",
    },
  ],
  "conv-5": [
    {
      id: "m14",
      conversationId: "conv-5",
      direction: "outbound",
      text: "Hi Java House team, attached is our Q3 campaign proposal covering 6 premium sites across Nairobi. Total reach: 1.2M impressions/week.",
      time: "6:00 AM",
      channel: "email",
      senderName: "Brian Mwangi",
    },
    {
      id: "m15",
      conversationId: "conv-5",
      direction: "inbound",
      text: "Please review the attached proposal for Q3 campaign",
      time: "6:30 AM",
      channel: "email",
      senderName: "Java House",
    },
  ],
  "conv-6": [
    {
      id: "m16",
      conversationId: "conv-6",
      direction: "inbound",
      text: "Hi, we're interested in your media placement services",
      time: "4:00 AM",
      channel: "whatsapp",
      senderName: "Unga Group",
    },
    {
      id: "m17",
      conversationId: "conv-6",
      direction: "outbound",
      text: "Thank you for reaching out! We've received your message and our team will get back to you within 2 hours. In the meantime, feel free to browse our available inventory at marketlink.co.ke/inventory",
      time: "4:01 AM",
      channel: "whatsapp",
          senderName: "Market Link",
          isAutomation: true,
        },
  ],
};

export const sampleInventory: InventoryItem[] = [
  {
    id: "inv-1",
    type: "Digital Screen",
    name: "Westlands Roundabout — Screen A",
    location: "Westlands, Nairobi",
    area: "Westlands",
    size: "6×3m",
    resolution: "1080p LED",
    dailyImpressions: 220000,
    price: 85000,
    status: "available",
    imageGradient: "from-[#1a1a2e] to-[#16213e]",
  },
  {
    id: "inv-2",
    type: "Billboard",
    name: "Mombasa Road Super-size",
    location: "Industrial Area, Nairobi",
    area: "Industrial Area",
    size: "12×4m",
    resolution: "Static Print",
    dailyImpressions: 180000,
    price: 120000,
    status: "available",
    imageGradient: "from-[#1a1a1a] to-[#2e2e2e]",
  },
  {
    id: "inv-3",
    type: "Billboard",
    name: "CBD Upper Hill Junction",
    location: "Upper Hill, Nairobi",
    area: "Upper Hill",
    size: "8×3m",
    resolution: "Backlit",
    dailyImpressions: 150000,
    price: 95000,
    status: "booked",
    bookedBy: "Safaricom",
    bookedUntil: "31 Jul 2026",
    imageGradient: "from-[#1a1a1a] to-[#2a2a2a]",
  },
  {
    id: "inv-4",
    type: "Digital Screen",
    name: "Thika Road Mall Entrance",
    location: "Kasarani, Nairobi",
    area: "Kasarani",
    size: "4×2.5m",
    resolution: "4K LED",
    dailyImpressions: 95000,
    price: 55000,
    status: "available",
    imageGradient: "from-[#1a1a2e] to-[#0f3460]",
  },
  {
    id: "inv-5",
    type: "Digital Screen",
    name: "Westlands Roundabout — Screen B",
    location: "Westlands, Nairobi",
    area: "Westlands",
    size: "6×3m",
    resolution: "1080p LED",
    dailyImpressions: 220000,
    price: 85000,
    status: "available",
    imageGradient: "from-[#1a1a2e] to-[#16213e]",
  },
  {
    id: "inv-6",
    type: "Billboard",
    name: "Nyayo Stadium Roundabout",
    location: "South C, Nairobi",
    area: "South C",
    size: "10×4m",
    resolution: "Static Print",
    dailyImpressions: 160000,
    price: 110000,
    status: "booked",
    bookedBy: "Airtel Kenya",
    bookedUntil: "15 Aug 2026",
    imageGradient: "from-[#1a1a1a] to-[#2e2e2e]",
  },
  {
    id: "inv-7",
    type: "Banner Site",
    name: "Kenyatta Avenue — East",
    location: "CBD, Nairobi",
    area: "CBD",
    size: "3×1.5m",
    resolution: "Flex Print",
    dailyImpressions: 45000,
    price: 35000,
    status: "available",
    imageGradient: "from-[#1a1a1a] to-[#2a2a2a]",
  },
  {
    id: "inv-8",
    type: "Billboard",
    name: "Waiyaki Way — Uthiru",
    location: "Uthiru, Nairobi",
    area: "Uthiru",
    size: "8×3m",
    resolution: "Static Print",
    dailyImpressions: 120000,
    price: 70000,
    status: "available",
    imageGradient: "from-[#1a1a1a] to-[#2e2e2e]",
  },
];

export const sampleBookings: Booking[] = [
  {
    id: "bk-1",
    clientId: "c1",
    clientName: "Safaricom",
    inventoryId: "inv-3",
    inventoryName: "CBD Upper Hill Junction",
    startDate: "2026-06-01",
    endDate: "2026-07-31",
    status: "confirmed",
    totalPrice: 190000,
    createdAt: "2026-05-15",
  },
  {
    id: "bk-2",
    clientId: "c2",
    clientName: "Airtel Kenya",
    inventoryId: "inv-6",
    inventoryName: "Nyayo Stadium Roundabout",
    startDate: "2026-06-10",
    endDate: "2026-08-15",
    status: "confirmed",
    totalPrice: 242000,
    createdAt: "2026-05-20",
  },
  {
    id: "bk-3",
    clientId: "c3",
    clientName: "P&G East Africa",
    inventoryId: "inv-1",
    inventoryName: "Westlands Roundabout — Screen A",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    status: "pending",
    totalPrice: 255000,
    createdAt: "2026-06-20",
  },
  {
    id: "bk-4",
    clientId: "c4",
    clientName: "Bidco Africa",
    inventoryId: "inv-2",
    inventoryName: "Mombasa Road Super-size",
    startDate: "2026-08-01",
    endDate: "2026-10-31",
    status: "pending",
    totalPrice: 360000,
    createdAt: "2026-06-22",
  },
  {
    id: "bk-5",
    clientId: "c5",
    clientName: "Java House",
    inventoryId: "inv-4",
    inventoryName: "Thika Road Mall Entrance",
    startDate: "2026-05-01",
    endDate: "2026-06-30",
    status: "completed",
    totalPrice: 110000,
    createdAt: "2026-04-10",
  },
];

export const sampleClients = [
  { id: "c1", name: "Safaricom" },
  { id: "c2", name: "Airtel Kenya" },
  { id: "c3", name: "P&G East Africa" },
  { id: "c4", name: "Bidco Africa" },
  { id: "c5", name: "Java House" },
  { id: "c6", name: "Twiga Foods" },
  { id: "c7", name: "Naivas" },
  { id: "c8", name: "Unga Group" },
];
