-- Seed demo analytics data for portal clients (DEPRECATED)
-- Migration 035 (ingest_kanini_real_data) truncates all analytics tables
-- and inserts real Kanini FMCG data, replacing any seed data from this
-- migration. This file is kept as a no-op to maintain migration sequence.
-- Do not insert anything here — 035 handles all data.
